permalink: /:categories/:title

collections:
  sang-penyampai-pesan:
    output: true
  pria-bertopeng-dari-surga:
    output: true
lembayung-senja:
output: true


 
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"
