layouts_dir         : _layouts
includes_dir        : _includes

collections:
    posts:
        output: true
        
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
markdown            : kramdown

permalink: :path
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"
