layouts_dir         : _layouts
includes_dir        : _includes

collections:
    posts:
        output: true
        
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
markdown            : kramdown

permalink: path
